// static reference data for London rail lines and stations, generated by
// prepare-transit.mjs into public/data/{tube-lines,stations}.geojson.

// London Overground was split into six named lines in Nov 2024; the source data
// predates that, so prepare-transit.mjs re-assigns each segment/station by route
// corridor (OVERGROUND_LINE_STATIONS below). colours are TfL's 2024 hexes.
export const OVERGROUND_LINE_COLOURS = {
  "Lioness line": "#f3b900", // yellow
  "Mildmay line": "#4e7ec0", // blue
  "Windrush line": "#ea4556", // red
  "Weaver line": "#9d275b", // maroon
  "Suffragette line": "#43b06f", // green
  "Liberty line": "#6f6b68", // grey
};

// canonical TfL line colours, keyed by the line name used in the output data
export const LINE_COLOURS = {
  Bakerloo: "#B36305",
  Central: "#E32017",
  Circle: "#FFD300",
  District: "#00782A",
  "Hammersmith & City": "#F3A9BB",
  Jubilee: "#A0A5A9",
  Metropolitan: "#9B0056",
  Northern: "#000000",
  Piccadilly: "#003688",
  Victoria: "#0098D4",
  "Waterloo & City": "#95CDBA",
  DLR: "#00A4A7",
  ...OVERGROUND_LINE_COLOURS,
  "London Overground": "#EE7C0E", // fallback for segments we couldn't classify
  "Elizabeth line": "#6950A1",
  Tramlink: "#84B817",
  "IFS Cloud Cable Car": "#E1251B",
};

// underground line names (the classic "tube"); the rest are other rail modes
export const UNDERGROUND_LINES = new Set([
  "Bakerloo",
  "Central",
  "Circle",
  "District",
  "Hammersmith & City",
  "Jubilee",
  "Metropolitan",
  "Northern",
  "Piccadilly",
  "Victoria",
  "Waterloo & City",
]);

export const OVERGROUND_LINES = new Set([
  ...Object.keys(OVERGROUND_LINE_COLOURS),
  "London Overground",
]);

// lines we render — anything else in the source (Crossrail 2, Thameslink...) is dropped
export const RENDERED_LINES = Object.keys(LINE_COLOURS);

// map a line name to a transport mode tag used on station points
export function lineToMode(name) {
  if (UNDERGROUND_LINES.has(name)) return "tube";
  if (name === "DLR") return "dlr";
  if (OVERGROUND_LINES.has(name) || name === "East London") return "overground";
  if (name === "Elizabeth line") return "elizabeth";
  if (name === "Tramlink") return "tram";
  if (name === "IFS Cloud Cable Car") return "cablecar";
  if (name === "National Rail" || name === "Thameslink 6tph line") return "nationalrail";
  return null;
}

export const MODE_LABELS = {
  tube: "Underground",
  dlr: "DLR",
  overground: "Overground",
  elizabeth: "Elizabeth line",
  tram: "Tram",
  cablecar: "Cable Car",
  nationalrail: "National Rail",
};

// normalise a station name for cross-dataset matching / de-duplication
export function normaliseStationName(name) {
  return String(name)
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/\((?:for [^)]+|[^)]+)\)/g, "")
    .replace(/\b(rail(way)?|underground|dlr|tram|national rail)?\s*station\b/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

// station lists for the six Overground lines (route corridors), used to classify
// the unlabelled "London Overground" geometry; shared stations appear twice
export const OVERGROUND_LINE_STATIONS = {
  "Lioness line": [
    "Euston", "South Hampstead", "Kilburn High Road", "Queen's Park", "Kensal Green",
    "Willesden Junction", "Harlesden", "Stonebridge Park", "Wembley Central", "North Wembley",
    "South Kenton", "Kenton", "Harrow & Wealdstone", "Headstone Lane", "Hatch End",
    "Carpenders Park", "Bushey", "Watford High Street", "Watford Junction",
  ],
  "Mildmay line": [
    "Stratford", "Hackney Wick", "Homerton", "Hackney Central", "Dalston Kingsland",
    "Canonbury", "Highbury & Islington", "Caledonian Road & Barnsbury", "Camden Road",
    "Kentish Town West", "Gospel Oak", "Hampstead Heath", "Finchley Road & Frognal",
    "West Hampstead", "Brondesbury", "Brondesbury Park", "Kensal Rise", "Willesden Junction",
    "Acton Central", "South Acton", "Gunnersbury", "Kew Gardens", "Richmond",
    "Shepherd's Bush", "Kensington (Olympia)", "West Brompton", "Imperial Wharf", "Clapham Junction",
  ],
  "Windrush line": [
    "Highbury & Islington", "Canonbury", "Dalston Junction", "Haggerston", "Hoxton",
    "Shoreditch High Street", "Whitechapel", "Shadwell", "Wapping", "Rotherhithe",
    "Canada Water", "Surrey Quays", "New Cross", "New Cross Gate", "Brockley", "Honor Oak Park",
    "Forest Hill", "Sydenham", "Penge West", "Anerley", "Norwood Junction", "West Croydon",
    "Crystal Palace", "Queens Road Peckham", "Peckham Rye", "Denmark Hill", "Clapham High Street",
    "Wandsworth Road", "Clapham Junction", "Battersea Park",
  ],
  "Weaver line": [
    "Liverpool Street", "Bethnal Green", "Cambridge Heath", "London Fields", "Hackney Downs",
    "Rectory Road", "Stoke Newington", "Stamford Hill", "Seven Sisters", "Bruce Grove",
    "White Hart Lane", "Silver Street", "Edmonton Green", "Southbury", "Turkey Street",
    "Theobalds Grove", "Cheshunt", "Bush Hill Park", "Enfield Town", "Clapton", "St James Street",
    "Walthamstow Central", "Wood Street", "Highams Park", "Chingford",
  ],
  "Suffragette line": [
    "Gospel Oak", "Upper Holloway", "Crouch Hill", "Harringay Green Lanes", "South Tottenham",
    "Blackhorse Road", "Walthamstow Queens Road", "Leyton Midland Road", "Leytonstone High Road",
    "Wanstead Park", "Woodgrange Park", "Barking", "Barking Riverside",
  ],
  "Liberty line": ["Romford", "Emerson Park", "Upminster"],
};

// which Overground line(s) a station name belongs to (by normalised name)
export function overgroundLinesForStation(name) {
  const norm = normaliseStationName(name);
  const out = [];
  for (const [line, stations] of Object.entries(OVERGROUND_LINE_STATIONS)) {
    if (stations.some((s) => normaliseStationName(s) === norm)) out.push(line);
  }
  return out;
}
